name: Tutorial Request
description: Blog or YouTube tutorial request form
title: "[Request]: "
labels: [blog, youtube]
assignees:
  - qainsights
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out my request form.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can I get in touch with you if we I more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: type
    attributes:
      label: Tutorial Type
      description: What type of content you want me to create?
      options:
        - Blog Article (Default)
        - YouTube
        - Course 
    validations:
      required: true
  - type: textarea
    id: tech-tools-list
    attributes:
      label: Please list out the technologies or tools involved.
      description: Also tell me, the specific version, platform etc.
      placeholder: List of technolgies and tools
      value: "e.g. JMeter, Locust etc"
    validations:
      required: true
  - type: textarea
    id: problem-desc
    attributes:
      label: Is your tutorial request related to a problem?
      description: 'Please describe your problem.'
      placeholder: Problem statement
      value: "Ex. I'm always frustrated when [...]"
    validations:
      required: true
  - type: dropdown
    id: sponsor
    attributes:
      label: Sponsor
      description: Are you willing to sponsor my content creation? Paid request will have higher priority.
      options:
        - Yes
        - No
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
